version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file: 
      - .env
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: go run main.go

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: npm run dev

  db:
    image: postgres:15
    restart: always
    env_file: 
      - .env 
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
