name: gohomeai
channels:
  - conda-forge
  - pytorch
dependencies:
  # core interpreter
  - python=3.11

  # tooling
  - black
  - isort
  - flake8
  - pre-commit
  - jupyterlab

  # data / ML
  - numpy<2
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly   # remove if use CUDA later

  # fastapi runtime
  - fastapi
  - uvicorn[standard]

  - pytest
  - pytest-cov 
  # pip extras, if any
  - pip:
      - transformers
      - sentencepiece