// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type Device struct {
	ID     int32  `json:"id"`
	Name   string `json:"name"`
	Status string `json:"status"`
}

type SystemMetric struct {
	ID          int32        `json:"id"`
	Timestamp   sql.NullTime `json:"timestamp"`
	CpuUsage    float64      `json:"cpu_usage"`
	MemoryUsed  int64        `json:"memory_used"`
	MemoryTotal int64        `json:"memory_total"`
	LoadAvg     float64      `json:"load_avg"`
	DiskUsed    int64        `json:"disk_used"`
	DiskTotal   int64        `json:"disk_total"`
}
